### PR TITLE
feat: add microdatas

### PR DESCRIPTION
**Pull request by Kocal**
**Summary**

This PR adds some microdatas on post and posts list. Microdatas are useful for search engines/web crawlers and can improve your position on search engines or the user experience.

Here are some screenshots on the [Google's Structured data Testing tool](https://search.google.com/structured-data/testing-tool):

**Homepage (before):**
Capture d’écran de 2020-02-04 21-08-12

**Homepage (after):**
Capture d’écran de 2020-02-04 21-07-06

**Post (before):**
Capture d’écran de 2020-02-04 21-39-49

**Post (after):**
Capture d’écran de 2020-02-04 21-35-31

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

No UI changes.

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome 79.0.3945.130
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [x] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

Nope.

### CODE REVIEW

**Comment by newsbielt703** [comment]
Nice! I'll review it ASAP.

**Comment by Kocal** [comment]
> Why not adding `publisher` property to author, too?

I wasn't really sure of how to use the microdata properly, but sure we can add it.

> Is `dateModified` really required since we're currently only displaying published date?

You're right, it's not displayed but I thought it can be intersting to still have the info somewhere. 
Maybe we should display it?

**Comment by newsbielt703** [comment]
IMO, we can provide an option whether to display last modified date, but it'll be another PR or issue, so leave `dateModified ` to it.

**Comment by Kocal** [comment]
I've added "publisher" micro-data:
Capture d’écran de 2020-02-11 20-52-00

**Comment by newsbielt703** [comment]
Cool, could you remove `dateModified` for now, and I'll merge it.

**Comment by Kocal** [comment]
Done

**Pull request merged**
